//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShamanPushAidServicioWinForm.MapaAndLicenceService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MapaAndLicenceService.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistanciaTiempo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetDistanciaTiempo(string latMov, string lngMov, string latDst, string lngDst);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistanciaTiempo", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetDistanciaTiempoAsync(string latMov, string lngMov, string latDst, string lngDst);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDireccion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetDireccion(string lat, string lng);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDireccion", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetDireccionAsync(string lat, string lng);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLatLong", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetLatLong(string direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLatLong", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetLatLongAsync(string direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPuntosEnPoligono", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPuntosEnPoligono(float pLat, float pLon, string pTip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPuntosEnPoligono", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetPuntosEnPoligonoAsync(float pLat, float pLon, string pTip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getIncidente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getIncidente(string cod, string fec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getIncidente", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getIncidenteAsync(string cod, string fec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSerialSetLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getSerialSetLog(string serialNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSerialSetLog", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getSerialSetLogAsync(string serialNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSerialSetLogLast", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getSerialSetLogLast(string serialNumber, int pRemote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSerialSetLogLast", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getSerialSetLogLastAsync(string serialNumber, int pRemote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isInGestion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string isInGestion(string user, string pass, string llave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isInGestion", ReplyAction="*")]
        System.Threading.Tasks.Task<string> isInGestionAsync(string user, string pass, string llave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setPushNotification", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool setPushNotification(string license, string mobile, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setPushNotification", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> setPushNotificationAsync(string license, string mobile, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getLicenseInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ShamanPushAidServicioWinForm.MapaAndLicenceService.LicenseInfo[] getLicenseInfo(string serialNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getLicenseInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<ShamanPushAidServicioWinForm.MapaAndLicenceService.LicenseInfo[]> getLicenseInfoAsync(string serialNumber);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LicenseInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serialNumberField;
        
        private int numeroField;
        
        private string jerarquiaField;
        
        private int estadoField;
        
        private System.DateTime vencimientoField;
        
        private string observacionesField;
        
        private System.DateTime vencimientoLicenciaField;
        
        private System.DateTime vencimientoSoporteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
                this.RaisePropertyChanged("SerialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("Numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Jerarquia {
            get {
                return this.jerarquiaField;
            }
            set {
                this.jerarquiaField = value;
                this.RaisePropertyChanged("Jerarquia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime Vencimiento {
            get {
                return this.vencimientoField;
            }
            set {
                this.vencimientoField = value;
                this.RaisePropertyChanged("Vencimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
                this.RaisePropertyChanged("Observaciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime VencimientoLicencia {
            get {
                return this.vencimientoLicenciaField;
            }
            set {
                this.vencimientoLicenciaField = value;
                this.RaisePropertyChanged("VencimientoLicencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime VencimientoSoporte {
            get {
                return this.vencimientoSoporteField;
            }
            set {
                this.vencimientoSoporteField = value;
                this.RaisePropertyChanged("VencimientoSoporte");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : ShamanPushAidServicioWinForm.MapaAndLicenceService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<ShamanPushAidServicioWinForm.MapaAndLicenceService.ServiceSoap>, ShamanPushAidServicioWinForm.MapaAndLicenceService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDistanciaTiempo(string latMov, string lngMov, string latDst, string lngDst) {
            return base.Channel.GetDistanciaTiempo(latMov, lngMov, latDst, lngDst);
        }
        
        public System.Threading.Tasks.Task<string> GetDistanciaTiempoAsync(string latMov, string lngMov, string latDst, string lngDst) {
            return base.Channel.GetDistanciaTiempoAsync(latMov, lngMov, latDst, lngDst);
        }
        
        public string GetDireccion(string lat, string lng) {
            return base.Channel.GetDireccion(lat, lng);
        }
        
        public System.Threading.Tasks.Task<string> GetDireccionAsync(string lat, string lng) {
            return base.Channel.GetDireccionAsync(lat, lng);
        }
        
        public string GetLatLong(string direccion) {
            return base.Channel.GetLatLong(direccion);
        }
        
        public System.Threading.Tasks.Task<string> GetLatLongAsync(string direccion) {
            return base.Channel.GetLatLongAsync(direccion);
        }
        
        public string GetPuntosEnPoligono(float pLat, float pLon, string pTip) {
            return base.Channel.GetPuntosEnPoligono(pLat, pLon, pTip);
        }
        
        public System.Threading.Tasks.Task<string> GetPuntosEnPoligonoAsync(float pLat, float pLon, string pTip) {
            return base.Channel.GetPuntosEnPoligonoAsync(pLat, pLon, pTip);
        }
        
        public string getIncidente(string cod, string fec) {
            return base.Channel.getIncidente(cod, fec);
        }
        
        public System.Threading.Tasks.Task<string> getIncidenteAsync(string cod, string fec) {
            return base.Channel.getIncidenteAsync(cod, fec);
        }
        
        public string getSerialSetLog(string serialNumber) {
            return base.Channel.getSerialSetLog(serialNumber);
        }
        
        public System.Threading.Tasks.Task<string> getSerialSetLogAsync(string serialNumber) {
            return base.Channel.getSerialSetLogAsync(serialNumber);
        }
        
        public string getSerialSetLogLast(string serialNumber, int pRemote) {
            return base.Channel.getSerialSetLogLast(serialNumber, pRemote);
        }
        
        public System.Threading.Tasks.Task<string> getSerialSetLogLastAsync(string serialNumber, int pRemote) {
            return base.Channel.getSerialSetLogLastAsync(serialNumber, pRemote);
        }
        
        public string isInGestion(string user, string pass, string llave) {
            return base.Channel.isInGestion(user, pass, llave);
        }
        
        public System.Threading.Tasks.Task<string> isInGestionAsync(string user, string pass, string llave) {
            return base.Channel.isInGestionAsync(user, pass, llave);
        }
        
        public bool setPushNotification(string license, string mobile, string message) {
            return base.Channel.setPushNotification(license, mobile, message);
        }
        
        public System.Threading.Tasks.Task<bool> setPushNotificationAsync(string license, string mobile, string message) {
            return base.Channel.setPushNotificationAsync(license, mobile, message);
        }
        
        public ShamanPushAidServicioWinForm.MapaAndLicenceService.LicenseInfo[] getLicenseInfo(string serialNumber) {
            return base.Channel.getLicenseInfo(serialNumber);
        }
        
        public System.Threading.Tasks.Task<ShamanPushAidServicioWinForm.MapaAndLicenceService.LicenseInfo[]> getLicenseInfoAsync(string serialNumber) {
            return base.Channel.getLicenseInfoAsync(serialNumber);
        }
    }
}
